### ISSUE TITLE
Cannot translate WooCommerce variable product attribute values

### ISSUE THREAD

**Issue by dieSuse** [qTranslate-Team/woocommerce-qtranslate-x#26]
Hi there,

sorry, maybe it is my fault, but I'm trying since hours and I have no idea anymore. 
I want to translate attribute values of a variable product. As described at "Known Issues" of this plugin I tried "[:de]wert1[:en]value1[:] | [:de]wert2[:en]value2[:]" or "{:de}wert1{:en}value1{:} | {:de}wert2{:en}value2{:}" but the select box at the front end always stays empty except the "Choose an option".
Translating the attribute name this way works fine, but the values won't.
If I just change the attribute value to "value1 | value2" (so, only English for testing) makes it work as supposed. That tells me, that all the other things are correct. Changing the attribute value back to qtranslate-code as seen above and the select box is empty again.

It's driving me crazy. So please help!

Regards,
Suse

Using WooCommerce version 2.5.2
WooCommerce&qTranslate-X version 1.3
(WooCommerce Germanized 1.5.1)

**Comment by dieSuse** [comment]
Hi found a solution. Maybe not a very elegant one but it works and it is update safe.

I found out, that the attribute values read out in woocommerce/includes/class-wc-product-variable.php are on the one hand ($assigned_text_attributes) the translated ones and on the other hand ($text_attributes) the raw ones using the qtranslate-x code [:de]...[:fr]...[:]. Of course this way, there were no matching values found and the select box stays empty.
I solved this issue but just translating the raw $text_attributes by myself.

Since changing the code in the core file is not update safe, I created a class My_WC_Product_Variable deriving from WC_Product_Variable. This class has only one method get_variation_attributes() where the foreach-loop to translate the attribute values is added.

In my funktions.php I managed to use class My_WC_Product_Variable and the select box is filled with correct translated attribue values.

**Comment by pjrobertson** [comment]
Hi @dieSuse I am currently encountering this problem right now.

Do you think you'd be able to provide the code in your My_WC_Product_Variable class and the functions.php class? It could then perhaps be used as a patch

**Comment by pjrobertson** [comment]
OK, my problem was that I changed the default language of my blog (from Chinese to English) so the attribute names were changed in Woocommerce from `attribute_NAME-CHINESE` to `attribute-NAME-ENGLISH` which meant the attributes weren't being found

**Comment by johnclause** [comment]
Yes, this would break many things and this probably does not help others.

However, the problem with variable attributes has been resolved a while ago. I am not sure if it was released though, I have to check, since something else is holding up, but you may take the latest version of integration plugin [here](https://github.com/qTranslate-Team/woocommerce-qtranslate-x/archive/master.zip) and it should work correctly. If it does not, please, submit a new issue with steps to reproduce the problem. Thanks a lot for testing.

**Comment by pjrobertson** [comment]
Yes, you are right. This issue is fixed (I have been using the latest HEAD for some time now).

My latest issue #32 is still valid even for the latest code

**Comment by cartabianca** [comment]
dieSuse, any chance to share your code? I'm dealing with the same problem you solved.
Thanks!

**Comment by dieSuse** [comment]
Hi Cartabianca,

I think this issue was correctly fixed from johnclause. So find the fixed plugin at his link [here](https://github.com/qTranslate-Team/woocommerce-qtranslate-x/archive/master.zip). 

If you still need my hack, I can have a look in my code from a looong time ago.

Regards,
dieSuse

**Comment by cartabianca** [comment]
Hello dieSuse,
I have tried your latest version (1.4) on my website, but it looks the problem is still there (see enclosed screenshot).

I would really appreciate if you can have a look at your code to see if an easy fix is possible.

Thanks a million!

---------------------------------------------
Diego Meozzi
Cartabianca Publishing snc
http://www.cartabianca.com
