### ISSUE TITLE
Woocommerce variation attributes should be re-saved when changing Qtranslate-x default language

### ISSUE THREAD

**Issue by pjrobertson** [qTranslate-Team/woocommerce-qtranslate-x#32]
Woocommerce internally uses the default qtranslate-x language for the attribute name keys. This means that if you change the default language, variation attribute keys are incorrect and no variations (options) display on product pages.

(e.g. if you look in woocommerce/includes/class-wc-product-variable.php at line 392 you'll see:
`$attribute_field_name = 'attribute_' . sanitize_title( $attribute['name'] );`

`$attribute['name']` is set to the name of the attribute for the default language, so if you change the default language then the `$attribute_field_name` value is wrong and no options are displayed.

To reproduce:
- Set up your blog with two languages (e.g. EN and DE)
- Set your default language to EN
- Create a new Woocommerce product, with a variation attribute (translated using `[:en]my attribute[:de]Mein attribute[:]` etc.)
- Save the product and check the product page. You should see a dropdown with options generated from your attribute
- Change your default blog language to DE.
- Go back to the product page and notice how the drop down box is empty.
- You can fix this bug by re-saving the product attribute from the admin side. I guess this re-generates the required keys once more in the default language

**Comment by johnclause** [comment]
I do not think it is an issue, since one is not supposed to change the default language: https://qtranslatexteam.wordpress.com/startup-guide/, see "Important" note for item 1.

We should put a big warning about it in the plugin when default language is changed, but it is not there yet - sorry. Changing the default language after the database is populated with translations is a very difficult operation, if not impossible in a general way, since we cannot know what other plugins do with the translated entries and how they are in use. Woocommerce is a an example of it

I do not think we should worry implementing a code to do this change. It is a very rare operation and should be done manually based on each particular case. 

I hope it is understandable. I am closing the issue now, we may keep writing into a closed issue or can re-open it if needed. Thanks a lot for your report.

**Comment by pjrobertson** [comment]
Fair enough, your response is reasonable. Can I then suggest that a notice/alert is added to the Wordpress admin when the default language is changed (this is a Qtranslate-x issue not woocommerce-qtranslate-x)

Something like:

"You have changed your default language. This may have serious consequences on your site. Please read Important note 1 here: xxxxx"

**Comment by johnclause** [comment]
Yes,we should/must have such note.
